server.port=8080
spring.application.name=ms-barriodigital-bff

# --- Reemplaza <TENANT_ID> con tu Directory (tenant) ID real de Azure AD ---
azure.tenant-id=${AZURE_TENANT_ID:92b9ffd8-4da1-4956-b85b-62654b654d25}
azure.api-client-id=${AZURE_API_CLIENT_ID:8b0cc19f-2671-49c7-beff-816087690691}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${azure.tenant-id}/v2.0

# URL del microservicio de dominio (el que maneja tu compañero)
services.requests.base-url=${REQUESTS_SERVICE_URL:http://localhost:8081}

logging.level.org.springframework.security=DEBUG
logging.level.cl.duoc.ms_barriodigital_bff=DEBUG